name: build
on:
  push:
     branches:
      - master
jobs:
  linting:
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
    - name: Setup Action
      uses: actions/checkout@v2
    - name: Install gofish
      run: |
        curl -fsSL https://raw.githubusercontent.com/fishworks/gofish/master/scripts/install.sh | bash
        gofish init
        eval $(gofish tank)
        rm -rf "$GOFISH_DEFAULT_RIG"
        cp -R .. "$GOFISH_DEFAULT_RIG"
    - name: gofish lint
      run: |
        for i in $(ls Food/); do
          package="${i%.*}"
          gofish lint Food/$i
          gofish install $package
        done

