name: Test installing all available fish food
on:
  push:
     branches:
      - master
jobs:
  install:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Action
      uses: actions/checkout@v2
    - name: Install gofish
      run: |
        curl -fsSL https://raw.githubusercontent.com/fishworks/gofish/master/scripts/install.sh | bash
        gofish init
    - name: gofish install
      run: |
        for i in $(gofish search | tail -n +2 | awk '{print $1}'); do
          gofish install $i
        done
